### ISSUE TITLE
for POW, more error tolerant hitting bad images

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/PDS-Pipelines-Frontends#12] opened 2020-05-11 23:11 UTC
Currently POW stops processing if it hits one corrupt image. Report failed image to user (or log) and continue.

**Comment by dpmayerUSGS** [comment] 2020-06-01 17:08
Duplicate of https://github.com/USGS-Astrogeology/PDS-Pipelines/issues/387
Fixed in https://github.com/USGS-Astrogeology/PDS-Pipelines/issues/394

**Closed** 2020-06-01 22:07 UTC
